### ISSUE TITLE
 TypeError: pchstr must be a non-empty string

### ISSUE THREAD

**Issue by ajinkyakambe** [JSCasts-episodes/ep17-admin-bro-startup-part2#1]
Example app listening at http://localhost:3000
(node:12364) UnhandledPromiseRejectionWarning: TypeError: pchstr must be a non-empty string
    at deserialize (C:\Users\ajinkya\Documents\Go projects\microservice\Logrocket CCI MZR\finaladminpanel2\ep17-admin-bro-startup-part2\node_modules\@phc\format\index.js:135:11)
    at Object.verify (C:\Users\ajinkya\Documents\Go projects\microservice\Logrocket CCI MZR\finaladminpanel2\ep17-admin-bro-startup-part2\node_modules\argon2\argon2.js:55:73)
    at Object.authenticate (C:\Users\ajinkya\Documents\Go projects\microservice\Logrocket CCI MZR\finaladminpanel2\ep17-admin-bro-startup-part2\src\admin.router.js:22:35)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Users\ajinkya\Documents\Go projects\microservice\Logrocket CCI MZR\finaladminpanel2\ep17-admin-bro-startup-part2\node_modules\admin-bro-expressjs\plugin.js:199:23
(node:12364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nagarajumadamshetti** [comment]
SOLVED:
the argon2 module has a function argon2.verify(parameterA,parameterB) if parameterA is null when passed to argon2.verify this error is raised by argon2. Hence we need to verify the parameters before passing them.
